### ISSUE TITLE
About link points to old org

### ISSUE THREAD

**Issue by bradbeck** [buildsec/ssf#170]
## Current Behavior

The link in the "About" section of the repo page still points to the doc site for the old org.
<img width="317" alt="image" src="https://user-images.githubusercontent.com/425664/160454141-683f5c97-98c4-4063-af08-ea634fd4377a.png">

## Expected Behavior

The link should be pointing to https://buildsec.github.io/ssf

**Comment by mlieberman85** [comment]
Fixed
