### ISSUE TITLE
Remove all references to Mike Lieberman's personal github

### ISSUE THREAD

**Issue by mlieberman85** [buildsec/ssf#7]
All images should be part of this org. Where applicable all code that will be specifically part of the SSF should be under this repo or at least under this org.

**Comment by mlieberman85** [comment]
[IMAGE=ghcr.io/mlieberman85/rust:latest](https://github.com/thesecuresoftwarefactory/ssf/blob/703126771c2ff036e19f2cffa693b71129903ab5/demos/build_with_ebpf/bad_cargo/build-docker.sh#L4) is the final line that references my personal github. Once that is removed we can close this issue.

**Comment by lmilbaum** [comment]
> [IMAGE=ghcr.io/mlieberman85/rust:latest](https://github.com/thesecuresoftwarefactory/ssf/blob/703126771c2ff036e19f2cffa693b71129903ab5/demos/build_with_ebpf/bad_cargo/build-docker.sh#L4) is the final line that references my personal github. Once that is removed we can close this issue.

I couldn't find any reference in the code to the build-docker.sh script. Could you please clarity in what situations this script is being used?

**Comment by mlieberman85** [comment]
[IMAGE=ghcr.io/mlieberman85/rust:latest](https://github.com/buildsec/ssf/blob/1899df28948ca37a1ca7cb20a82ff17928f8b972/demos/build_with_ebpf/bad_cargo/build-docker.sh#L4) It is this line in one of the demos.

**Comment by lmilbaum** [comment]
> [IMAGE=ghcr.io/mlieberman85/rust:latest](https://github.com/buildsec/ssf/blob/1899df28948ca37a1ca7cb20a82ff17928f8b972/demos/build_with_ebpf/bad_cargo/build-docker.sh#L4) It is this line in one of the demos.

Yeah. I've noticed this line in the build-docker.sh script. Let me clarify my question.  Where can I find the instructions on how to execute the demo?
